// packages/angular/src/button.ts
import { Component } from "@angular/core";
import { type ButtonSize, type ButtonVariant, getButtonClassName } from "./button-utils.js";

@Component({
  selector: "foundry-button",
  standalone: true,
  inputs: ["variant", "size", "type", "disabled", "ariaLabel", "className", "label"],
  template: `
    <button
      [type]="type"
      [disabled]="disabled"
      [class]="classes"
      [attr.aria-label]="ariaLabel"
      [attr.aria-pressed]="ariaPressed"
    >
      <ng-content>{{ label }}</ng-content>
    </button>
  `,
})
export class ButtonComponent {
  variant: ButtonVariant = "default";
  size: ButtonSize = "default";
  type: "button" | "submit" | "reset" = "button";
  disabled = false;
  ariaLabel: string | null = null;
  ariaPressed: "true" | "false" | null = null;
  className = "";
  label = "Button";

  get classes(): string {
    return getButtonClassName(this.variant, this.size, this.className);
  }
}

export { getButtonClassName } from "./button-utils.js";
export type { ButtonSize, ButtonVariant } from "./button-utils.js";

// packages/svelte/src/Button.svelte
<script lang="ts">
  import { getButtonClassName, type ButtonSize, type ButtonVariant } from "./button.js";

  export let variant: ButtonVariant = "default";
  export let size: ButtonSize = "default";
  export let type: "button" | "submit" | "reset" = "button";
  export let disabled = false;
  export let ariaLabel: string | undefined = undefined;
  export let className = "";
</script>

<button
  type={type}
  disabled={disabled}
  aria-label={ariaLabel}
  class={getButtonClassName(variant, size, className)}
  on:click
>
  <slot>Button</slot>
</button>
