// packages/angular/src/emitter-strategies.ts
import type { TransformedComponent } from "@shadcnui-foundry/core";
import type {
  ComponentIR,
  GeneratedFile,
  PipelineResult,
  Prop,
  Variant,
} from "@shadcnui-foundry/ir";

export type AngularEmitStrategyContext = {
  transformed: TransformedComponent;
  componentName: string;
  ir?: ComponentIR;
};

export type AngularEmitStrategy = (
  context: AngularEmitStrategyContext,
) => PipelineResult<GeneratedFile[]>;

function isIdentifier(value: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);
}

function toPascalCase(value: string): string {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function toSafeIdentifier(value: string): string {
  if (isIdentifier(value)) {
    return value;
  }

  const normalized = value
    .replace(/[^A-Za-z0-9_$]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter((part) => part.length > 0)
    .map((part, index) =>
      index === 0
        ? part.charAt(0).toLowerCase() + part.slice(1)
        : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join("");

  if (normalized.length > 0 && isIdentifier(normalized)) {
    return normalized;
  }

  return `prop${toPascalCase(value.replace(/[^A-Za-z0-9]+/g, "-"))}`;
}

function mapPropTypeToTs(prop: Prop): string {
  if ((prop.type === "enum" || prop.type === "union") && prop.values && prop.values.length > 0) {
    return prop.values.map((value) => `"${value}"`).join(" | ");
  }

  switch (prop.type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return "unknown[]";
    case "object":
      return "Record<string, unknown>";
    case "function":
      return "(...args: unknown[]) => unknown";
    case "node":
    case "ref":
    case "union":
      return "unknown";
    case "enum":
      return "string";
    default:
      return "unknown";
  }
}

function inferDefaultValue(prop: Prop): string | undefined {
  if (typeof prop.defaultValue === "string" && prop.defaultValue.trim().length > 0) {
    return prop.defaultValue;
  }

  if (prop.type === "boolean") {
    return "false";
  }

  if (prop.type === "string") {
    return '""';
  }

  return undefined;
}

function createInputFields(props: Prop[]): string {
  if (props.length === 0) {
    return "";
  }

  const usedIdentifiers = new Set<string>();

  return props
    .map((prop) => {
      const tsType = mapPropTypeToTs(prop);
      const defaultValue = inferDefaultValue(prop);
      const optionalSuffix = prop.required ? "" : "?";
      const initializer = defaultValue !== undefined ? ` = ${defaultValue}` : "";
      let inputFieldName = toSafeIdentifier(prop.name);
      let suffix = 1;
      while (usedIdentifiers.has(inputFieldName)) {
        inputFieldName = `${toSafeIdentifier(prop.name)}${suffix}`;
        suffix += 1;
      }
      usedIdentifiers.add(inputFieldName);

      const decorator = prop.name === inputFieldName ? "@Input()" : `@Input("${prop.name}")`;
      return `  ${decorator} ${inputFieldName}${optionalSuffix}: ${tsType}${initializer};`;
    })
    .join("\n");
}

function mergeVariantProps(props: Prop[], variants: Variant[]): Prop[] {
  const byName = new Map<string, Prop>();

  for (const prop of props) {
    byName.set(prop.name, prop);
  }

  for (const variant of variants) {
    if (byName.has(variant.name)) {
      continue;
    }

    byName.set(variant.name, {
      name: variant.name,
      type: "enum",
      values: variant.values,
      required: false,
      defaultValue: variant.defaultValue ? `"${variant.defaultValue}"` : undefined,
      forwarded: false,
    });
  }

  return [...byName.values()]
    .filter((prop) => prop.name !== "children")
    .sort((a, b) => a.name.localeCompare(b.name));
}

function mapOverlayTag(role: string | undefined): string {
  switch (role) {
    case "textbox":
      return "input";
    case "button":
      return "button";
    case "checkbox":
      return "input";
    case "switch":
      return "button";
    case "tab":
      return "button";
    case "menu":
      return "ul";
    case "menuitem":
      return "li";
    case "listbox":
      return "ul";
    case "option":
      return "li";
    case "navigation":
      return "nav";
    case "dialog":
      return "dialog";
    default:
      return "div";
  }
}

function emitAccordion({
  transformed,
  componentName,
}: AngularEmitStrategyContext): PipelineResult<GeneratedFile[]> {
  const content = `// @generated by shadcnui-foundry — DO NOT EDIT MANUALLY
// Run \`foundry generate ${transformed.componentId}\` to regenerate
import {
  AfterContentInit,
  Component,
  ContentChildren,
  Directive,
  HostBinding,
  Input,
  QueryList,
} from "@angular/core";

@Directive({
  selector: "[foundryAccordionItem]",
  standalone: true,
})
export class FoundryAccordionItemDirective {
  @Input() value = "";

  @HostBinding("attr.data-state")
  state: "open" | "closed" = "closed";

  setOpen(open: boolean): void {
    this.state = open ? "open" : "closed";
  }
}

@Component({
  selector: "foundry-${transformed.componentId}",
  standalone: true,
  template: \`
    <div class="accordion" role="presentation">
      <ng-content />
    </div>
  \`,
  imports: [FoundryAccordionItemDirective],
})
export class ${componentName}Component implements AfterContentInit {
  @Input() type: "single" | "multiple" = "single";
  @Input() collapsible = false;
  @Input() value: string | string[] | null = null;

  @ContentChildren(FoundryAccordionItemDirective)
  readonly items!: QueryList<FoundryAccordionItemDirective>;

  ngAfterContentInit(): void {
    this.syncItems();
    this.items.changes.subscribe(() => this.syncItems());
  }

  isItemOpen(itemValue: string): boolean {
    if (this.type === "multiple") {
      return Array.isArray(this.value) && this.value.includes(itemValue);
    }

    return this.value === itemValue;
  }

  toggleItem(itemValue: string): void {
    if (this.type === "multiple") {
      const current = Array.isArray(this.value) ? [...this.value] : [];
      const index = current.indexOf(itemValue);

      if (index >= 0) {
        current.splice(index, 1);
      } else {
        current.push(itemValue);
      }

      this.value = current;
      this.syncItems();
      return;
    }

    const isOpen = this.value === itemValue;
    this.value = isOpen && this.collapsible ? null : itemValue;
    this.syncItems();
  }

  private syncItems(): void {
    for (const item of this.items.toArray()) {
      item.setOpen(this.isItemOpen(item.value));
    }
  }
}
`;

  return {
    success: true,
    data: [
      {
        path: `${transformed.componentId}/${transformed.componentId}.component.ts`,
        content,
        componentId: transformed.componentId,
        framework: "angular",
        generated: true,
        irHash: "",
      },
    ],
  };
}

function emitDefault({
  transformed,
  componentName,
  ir,
}: AngularEmitStrategyContext): PipelineResult<GeneratedFile[]> {
  const selector = `foundry-${transformed.componentId}`;
  const isOverlayComponent = ["dialog", "popover", "dropdown-menu", "select"].includes(
    transformed.componentId,
  );
  const overlayRole = ir?.a11y.roles[0];
  const overlayTag = mapOverlayTag(overlayRole);
  const props = ir ? mergeVariantProps(ir.props, ir.variants) : [];
  const inputFields = createInputFields(props);
  const usesInputs = inputFields.length > 0;
  const shouldUseOverlayClass = isOverlayComponent;

  const imports = shouldUseOverlayClass
    ? usesInputs
      ? "{ Component, ElementRef, HostListener, Input, OnDestroy, OnInit, Renderer2, inject }"
      : "{ Component, ElementRef, HostListener, OnDestroy, OnInit, Renderer2, inject }"
    : usesInputs
      ? "{ Component, Input }"
      : "{ Component }";

  const overlayTemplate = isOverlayComponent
    ? `  template: \`
    <button type=\"button\" class=\"${transformed.componentId}-trigger\" (click)=\"openOverlay()\">Open</button>
    <${overlayTag}
      *ngIf=\"open\"
      class=\"${transformed.componentId} overlay\"
      tabindex=\"-1\"
      [attr.role]=\"'${overlayRole ?? ""}'\"
      [attr.data-foundry-overlay]=\"'${transformed.componentId}'\"
    >
      <ng-content />
    </${overlayTag}>
  \`,`
    : `  template: \`
    <div class=\"${transformed.componentId}\">
      <ng-content />
    </div>
  \`,`;

  const overlayClassBody = isOverlayComponent
    ? `
  readonly host = inject(ElementRef<HTMLElement>);
  readonly renderer = inject(Renderer2);
  open = false;

  ngOnInit(): void {
    // Portal rendering strategy: move host into document.body for overlay components.
    this.renderer.appendChild(document.body, this.host.nativeElement);
  }

  ngOnDestroy(): void {
    this.renderer.removeChild(document.body, this.host.nativeElement);
  }

  openOverlay(): void {
    this.open = true;
  }

  @HostListener("document:keydown", ["$event"])
  onDocumentKeydown(event: KeyboardEvent): void {
    if (!this.open) return;
    if (event.key === "Escape") {
      this.open = false;
      return;
    }

    if (event.key !== "Tab") return;

    const root = this.host.nativeElement.querySelector<HTMLElement>("[data-foundry-overlay=\\"${transformed.componentId}\\"]");
    if (!root) return;
    const focusable = root.querySelectorAll<HTMLElement>(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
    );
    if (focusable.length === 0) return;

    const first = focusable[0];
    const last = focusable[focusable.length - 1];

    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last?.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first?.focus();
    }
  }
`
    : "";

  const classImplements = shouldUseOverlayClass ? " implements OnInit, OnDestroy" : "";
  const classBodySections = [inputFields, overlayClassBody].filter((section) => section.length > 0);
  const classBody = classBodySections.join("\n");

  const content = `// @generated by shadcnui-foundry — DO NOT EDIT MANUALLY
// Run \`foundry generate ${transformed.componentId}\` to regenerate
import ${imports} from "@angular/core";

@Component({
  selector: "${selector}",
  standalone: true,
${overlayTemplate}
})
export class ${componentName}Component${classImplements} {
${classBody}
}
`;

  return {
    success: true,
    data: [
      {
        path: `${transformed.componentId}/${transformed.componentId}.component.ts`,
        content,
        componentId: transformed.componentId,
        framework: "angular",
        generated: true,
        irHash: "",
      },
    ],
  };
}

const COMPONENT_STRATEGIES: Record<string, AngularEmitStrategy> = {
  accordion: emitAccordion,
};

export function resolveAngularEmitStrategy(componentId: string): AngularEmitStrategy {
  return COMPONENT_STRATEGIES[componentId] ?? emitDefault;
}

export function getAngularEmitContext(
  transformed: TransformedComponent,
): AngularEmitStrategyContext {
  return {
    transformed,
    componentName: toPascalCase(transformed.componentId),
    ir: (transformed.spec as { ir?: ComponentIR }).ir,
  };
}

// packages/lit/src/emitter-strategies.ts
import type { TransformedComponent } from "@shadcnui-foundry/core";
import type {
  ComponentIR,
  GeneratedFile,
  PipelineResult,
  Prop,
  Variant,
} from "@shadcnui-foundry/ir";

export type LitEmitStrategyContext = {
  transformed: TransformedComponent;
  ir?: ComponentIR;
};

export type LitEmitStrategy = (context: LitEmitStrategyContext) => PipelineResult<GeneratedFile[]>;

function toPascalCase(value: string): string {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function isIdentifier(value: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);
}

function toSafeIdentifier(value: string): string {
  if (isIdentifier(value)) {
    return value;
  }

  const normalized = value
    .replace(/[^A-Za-z0-9_$]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter((part) => part.length > 0)
    .map((part, index) =>
      index === 0
        ? part.charAt(0).toLowerCase() + part.slice(1)
        : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join("");

  if (normalized.length > 0 && isIdentifier(normalized)) {
    return normalized;
  }

  return `prop${toPascalCase(value.replace(/[^A-Za-z0-9]+/g, "-"))}`;
}

function mapBaseTag(role: string | undefined): string {
  switch (role) {
    case "button":
      return "button";
    case "textbox":
      return "input";
    case "checkbox":
      return "input";
    case "switch":
      return "button";
    case "tab":
      return "button";
    case "menu":
      return "ul";
    case "menuitem":
      return "li";
    case "listbox":
      return "ul";
    case "option":
      return "li";
    case "navigation":
      return "nav";
    case "dialog":
      return "dialog";
    default:
      return "div";
  }
}

function mapPropertyType(prop: Prop): string {
  if ((prop.type === "enum" || prop.type === "union") && prop.values && prop.values.length > 0) {
    return prop.values.map((value) => `"${value}"`).join(" | ");
  }

  switch (prop.type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return "unknown[]";
    case "object":
      return "Record<string, unknown>";
    case "function":
      return "(...args: unknown[]) => unknown";
    default:
      return "unknown";
  }
}

function ensureVariantProps(props: Prop[], variants: Variant[]): Prop[] {
  const merged = new Map<string, Prop>();

  for (const prop of props) {
    merged.set(prop.name, prop);
  }

  for (const variant of variants) {
    if (merged.has(variant.name)) {
      continue;
    }

    merged.set(variant.name, {
      name: variant.name,
      type: "enum",
      values: variant.values,
      required: false,
      ...(variant.defaultValue !== undefined && { defaultValue: `"${variant.defaultValue}"` }),
      forwarded: false,
      description: `Variant: ${variant.name}`,
    });
  }

  return [...merged.values()]
    .filter((prop) => prop.name !== "children")
    .sort((a, b) => a.name.localeCompare(b.name));
}

function inferDefault(prop: Prop): string | undefined {
  if (prop.defaultValue !== undefined) {
    return prop.defaultValue;
  }

  if (prop.type === "boolean") {
    return "false";
  }

  return undefined;
}

function emitDefault({ transformed, ir }: LitEmitStrategyContext): PipelineResult<GeneratedFile[]> {
  const componentName = toPascalCase(transformed.componentId);
  const tagName = `foundry-${transformed.componentId}`;
  const isOverlayComponent = ["dialog", "popover", "dropdown-menu", "select"].includes(
    transformed.componentId,
  );
  const props = ir ? ensureVariantProps(ir.props, ir.variants) : [];
  const ariaAttrs = ir
    ? [...new Set([...ir.a11y.requiredAttributes, ...ir.a11y.optionalAttributes])].filter((attr) =>
        attr.startsWith("aria-"),
      )
    : [];

  const allProps: Prop[] = [
    ...props,
    ...ariaAttrs
      .filter((attr) => !props.some((prop) => prop.name === attr))
      .map((attr) => ({
        name: attr,
        type: "string" as const,
        required: false,
        forwarded: false,
        description: `Accessibility attribute: ${attr}`,
      })),
  ];

  const sortedAllProps = [...allProps].sort((a, b) => a.name.localeCompare(b.name));
  const propBindingByName = new Map<string, string>();
  const usedIdentifiers = new Set<string>();

  for (const prop of sortedAllProps) {
    let identifier = toSafeIdentifier(prop.name);
    let suffix = 1;
    while (usedIdentifiers.has(identifier)) {
      identifier = `${toSafeIdentifier(prop.name)}${suffix}`;
      suffix += 1;
    }
    usedIdentifiers.add(identifier);
    propBindingByName.set(prop.name, identifier);
  }

  const propertyLines = sortedAllProps.map((prop) => {
    const type = mapPropertyType(prop);
    const defaultValue = inferDefault(prop);
    const init = defaultValue !== undefined ? ` = ${defaultValue}` : "";
    const binding = propBindingByName.get(prop.name);
    if (!binding) {
      return "";
    }
    return `  @property({ attribute: ${JSON.stringify(prop.name)} }) ${binding}!: ${type}${init};`;
  });

  const variantAttrs = ir
    ? [...ir.variants]
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((variant) => {
          const binding = propBindingByName.get(variant.name) ?? toSafeIdentifier(variant.name);
          return `      data-${variant.name}=\"\${this.${binding} ?? ""}\"`;
        })
        .join("\n")
    : "";

  const ariaBindings = sortedAllProps
    .filter((prop) => prop.name.startsWith("aria-"))
    .map((prop) => {
      const binding = propBindingByName.get(prop.name) ?? toSafeIdentifier(prop.name);
      return `      ${prop.name}=\"\${this.${binding} ?? ""}\"`;
    })
    .join("\n");

  const role = ir?.a11y.roles[0];
  const roleLine = role ? `      role=\"${role}\"\n` : "";
  const baseTag = mapBaseTag(role);

  const overlayMembers = isOverlayComponent
    ? `  @property({ type: Boolean }) open = false;

  private onDocumentKeydown = (event: KeyboardEvent): void => {
    if (!this.open) return;
    if (event.key === "Escape") {
      this.open = false;
      return;
    }

    if (event.key !== "Tab") return;

    const root = this.renderRoot.querySelector<HTMLElement>("[data-foundry-overlay=\"${transformed.componentId}\"]");
    if (!root) return;
    const focusable = root.querySelectorAll<HTMLElement>(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
    );
    if (focusable.length === 0) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];

    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last?.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first?.focus();
    }
  };

  override connectedCallback(): void {
    super.connectedCallback();
    document.addEventListener("keydown", this.onDocumentKeydown);
  }

  override disconnectedCallback(): void {
    document.removeEventListener("keydown", this.onDocumentKeydown);
    super.disconnectedCallback();
  }
`
    : "";

  const overlayMembersBlock = overlayMembers.length > 0 ? `${overlayMembers}\n` : "";
  const classSpacer = overlayMembers.length > 0 ? "\n" : "";

  const overlayRender = isOverlayComponent
    ? `    if (!this.open) {
      return html\`<button class=\"${transformed.componentId}-trigger\" @click=\${() => (this.open = true)}>Open</button>\`;
    }

    // Portal rendering strategy: keep host mounted while overlay content is fixed and body-level layered.
    return html\`
      <${baseTag}
        data-foundry-overlay=\"${transformed.componentId}\"
${roleLine}${variantAttrs}
${ariaBindings}
        style=\"position: fixed; inset: 0; z-index: 1000;\"
      >
        <slot></slot>
      </${baseTag}>
    \`;`
    : `    return html\`
      <${baseTag}
${roleLine}${variantAttrs}
${ariaBindings}
      >
        <slot></slot>
      </${baseTag}>
    \`;`;

  const content = `// @generated by shadcnui-foundry — DO NOT EDIT MANUALLY
// Run \`foundry generate ${transformed.componentId}\` to regenerate
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";

@customElement("${tagName}")
export class ${componentName}Element extends LitElement {
${propertyLines.join("\n")}
${overlayMembersBlock}${classSpacer}
  override render() {
${overlayRender}
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "${tagName}": ${componentName}Element;
  }
}
`;
  return {
    success: true,
    data: [
      {
        path: `${transformed.componentId}/${tagName}.ts`,
        content,
        componentId: transformed.componentId,
        framework: "lit",
        generated: true,
        irHash: "",
      },
    ],
  };
}

function emitAccordion({ transformed }: LitEmitStrategyContext): PipelineResult<GeneratedFile[]> {
  const componentName = toPascalCase(transformed.componentId);
  const tagName = `foundry-${transformed.componentId}`;
  const content = `// @generated by shadcnui-foundry — DO NOT EDIT MANUALLY
// Run \`foundry generate ${transformed.componentId}\` to regenerate
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";

@customElement("${tagName}")
export class ${componentName}Element extends LitElement {
  @property({ type: String }) type: "single" | "multiple" = "single";

  @property({ type: Boolean }) collapsible = false;

  @property({ attribute: false }) value: string | string[] | undefined = undefined;

  @property({ attribute: false }) defaultValue: string | string[] | undefined = undefined;

  private get currentValue(): string | string[] | undefined {
    return this.value ?? this.defaultValue;
  }

  private get openCount(): number {
    const current = this.currentValue;
    if (Array.isArray(current)) {
      return current.length;
    }

    return typeof current === "string" && current.length > 0 ? 1 : 0;
  }

  private setValue(nextValue: string | string[]): void {
    if (this.value === undefined) {
      this.defaultValue = nextValue;
    }
    this.dispatchEvent(new CustomEvent<string | string[]>("value-change", { detail: nextValue }));
  }

  private toggleItem(itemValue: string): void {
    const current = this.currentValue;
    if (this.type === "multiple") {
      const next = Array.isArray(current)
        ? [...current]
        : typeof current === "string" && current.length > 0
          ? [current]
          : [];
      const index = next.indexOf(itemValue);
      if (index >= 0) {
        next.splice(index, 1);
      } else {
        next.push(itemValue);
      }

      this.setValue(next);
      return;
    }

    if (current === itemValue) {
      this.setValue(this.collapsible ? "" : itemValue);
      return;
    }

    this.setValue(itemValue);
  }

  override render() {
    return html\`
      <div
        role="presentation"
        data-component="accordion"
        data-type="\${this.type}"
        data-open-count="\${this.openCount}"
        @keydown=\${(event: KeyboardEvent) => {
          if (event.key !== "Enter" && event.key !== " ") return;
          const target = event.target as HTMLElement | null;
          const itemValue = target?.dataset.accordionValue;
          if (!itemValue) return;
          event.preventDefault();
          this.toggleItem(itemValue);
        }}
      >
        <slot></slot>
      </div>
    \`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "${tagName}": ${componentName}Element;
  }
}
`;

  return {
    success: true,
    data: [
      {
        path: `${transformed.componentId}/${tagName}.ts`,
        content,
        componentId: transformed.componentId,
        framework: "lit",
        generated: true,
        irHash: "",
      },
    ],
  };
}

const COMPONENT_STRATEGIES: Record<string, LitEmitStrategy> = {
  accordion: emitAccordion,
};

export function resolveLitEmitStrategy(componentId: string): LitEmitStrategy {
  return COMPONENT_STRATEGIES[componentId] ?? emitDefault;
}

export function getLitEmitContext(transformed: TransformedComponent): LitEmitStrategyContext {
  const ir = (transformed.spec as { ir?: ComponentIR }).ir;
  return {
    transformed,
    ...(ir !== undefined ? { ir } : {}),
  };
}
