// packages/lit/src/emitter.ts
import type { Emitter, TransformedComponent } from "@shadcnui-foundry/core";
import type {
  ComponentIR,
  GeneratedFile,
  PipelineResult,
  Prop,
  Variant,
} from "@shadcnui-foundry/ir";

function toPascalCase(value: string): string {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function mapBaseTag(role: string | undefined): string {
  switch (role) {
    case "button":
      return "button";
    case "textbox":
      return "input";
    default:
      return "div";
  }
}

function mapPropertyType(prop: Prop): string {
  if ((prop.type === "enum" || prop.type === "union") && prop.values && prop.values.length > 0) {
    return prop.values.map((value) => `"${value}"`).join(" | ");
  }

  switch (prop.type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return "unknown[]";
    case "object":
      return "Record<string, unknown>";
    case "function":
      return "(...args: unknown[]) => unknown";
    default:
      return "unknown";
  }
}

function ensureVariantProps(props: Prop[], variants: Variant[]): Prop[] {
  const merged = new Map<string, Prop>();

  for (const prop of props) {
    merged.set(prop.name, prop);
  }

  for (const variant of variants) {
    if (merged.has(variant.name)) {
      continue;
    }

    merged.set(variant.name, {
      name: variant.name,
      type: "enum",
      values: variant.values,
      required: false,
      ...(variant.defaultValue !== undefined && { defaultValue: `"${variant.defaultValue}"` }),
      forwarded: false,
      description: `Variant: ${variant.name}`,
    });
  }

  return [...merged.values()].filter((prop) => prop.name !== "children");
}

function inferDefault(prop: Prop): string | undefined {
  if (prop.defaultValue !== undefined) {
    return prop.defaultValue;
  }

  if (prop.type === "boolean") {
    return "false";
  }

  return undefined;
}

export class LitEmitter implements Emitter {
  readonly framework = "lit";

  async emit(transformed: TransformedComponent): Promise<PipelineResult<GeneratedFile[]>> {
    const componentName = toPascalCase(transformed.componentId);
    const tagName = `foundry-${transformed.componentId}`;
    const isOverlayComponent = ["dialog", "popover", "dropdown-menu", "select"].includes(
      transformed.componentId,
    );
    const ir = (transformed.spec as { ir?: ComponentIR }).ir;
    const props = ir ? ensureVariantProps(ir.props, ir.variants) : [];
    const ariaAttrs = ir
      ? [...new Set([...ir.a11y.requiredAttributes, ...ir.a11y.optionalAttributes])].filter(
          (attr) => attr.startsWith("aria-"),
        )
      : [];

    const allProps: Prop[] = [
      ...props,
      ...ariaAttrs
        .filter((attr) => !props.some((prop) => prop.name === attr))
        .map((attr) => ({
          name: attr,
          type: "string" as const,
          required: false,
          forwarded: false,
          description: `Accessibility attribute: ${attr}`,
        })),
    ];

    const propertyLines = allProps
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((prop) => {
        const type = mapPropertyType(prop);
        const defaultValue = inferDefault(prop);
        const init = defaultValue !== undefined ? ` = ${defaultValue}` : "";
        return `  @property({ attribute: ${JSON.stringify(prop.name)} }) ${JSON.stringify(prop.name)}!: ${type}${init};`;
      });

    const variantAttrs = ir
      ? ir.variants
          .map((variant) => `      data-${variant.name}=\"\${this[\"${variant.name}\"] ?? ""}\"`)
          .join("\n")
      : "";

    const ariaBindings = allProps
      .filter((prop) => prop.name.startsWith("aria-"))
      .map((prop) => `      ${prop.name}=\"\${this[\"${prop.name}\"] ?? ""}\"`)
      .join("\n");

    const role = ir?.a11y.roles[0];
    const roleLine = role ? `      role=\"${role}\"\n` : "";
    const baseTag = mapBaseTag(role);

    const overlayMembers = isOverlayComponent
      ? `  @property({ type: Boolean }) open = false;

  private onDocumentKeydown = (event: KeyboardEvent): void => {
    if (!this.open) return;
    if (event.key === "Escape") {
      this.open = false;
      return;
    }

    if (event.key !== "Tab") return;

    const root = this.renderRoot.querySelector<HTMLElement>("[data-foundry-overlay=\"${transformed.componentId}\"]");
    if (!root) return;
    const focusable = root.querySelectorAll<HTMLElement>(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
    );
    if (focusable.length === 0) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];

    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last?.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first?.focus();
    }
  };

  override connectedCallback(): void {
    super.connectedCallback();
    document.addEventListener("keydown", this.onDocumentKeydown);
  }

  override disconnectedCallback(): void {
    document.removeEventListener("keydown", this.onDocumentKeydown);
    super.disconnectedCallback();
  }
`
      : "";

    const overlayMembersBlock = overlayMembers.length > 0 ? `${overlayMembers}\n` : "";
    const classSpacer = overlayMembers.length > 0 ? "\n" : "";

    const overlayRender = isOverlayComponent
      ? `    if (!this.open) {
      return html\`<button class=\"${transformed.componentId}-trigger\" @click=\${() => (this.open = true)}>Open</button>\`;
    }

    // Portal rendering strategy: keep host mounted while overlay content is fixed and body-level layered.
    return html\`
      <${baseTag}
        data-foundry-overlay=\"${transformed.componentId}\"
${roleLine}${variantAttrs}
${ariaBindings}
        style=\"position: fixed; inset: 0; z-index: 1000;\"
      >
        <slot></slot>
      </${baseTag}>
    \`;`
      : `    return html\`
      <${baseTag}
${roleLine}${variantAttrs}
${ariaBindings}
      >
        <slot></slot>
      </${baseTag}>
    \`;`;

    const content = `// @generated by shadcnui-foundry — DO NOT EDIT MANUALLY
// Run \`foundry generate ${transformed.componentId}\` to regenerate
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";

@customElement("${tagName}")
export class ${componentName}Element extends LitElement {
${propertyLines.join("\n")}
${overlayMembersBlock}${classSpacer}
  override render() {
${overlayRender}
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "${tagName}": ${componentName}Element;
  }
}
`;
    return {
      success: true,
      data: [
        {
          path: `${transformed.componentId}/${tagName}.ts`,
          content,
          componentId: transformed.componentId,
          framework: "lit",
          generated: true,
          irHash: "",
        },
      ],
    };
  }
}

// packages/react/src/emitter.ts
import type { Emitter, TransformedComponent } from "@shadcnui-foundry/core";
import type { GeneratedFile, PipelineResult } from "@shadcnui-foundry/ir";

type ReactPropSpec = {
  name: string;
  type: string;
  required: boolean;
  defaultValue?: string;
  description?: string;
};

type ReactVariantSpec = {
  name: string;
  values: string[];
  defaultValue?: string;
};

type ReactA11ySpec = {
  roles: string[];
  requiredAttributes: string[];
  optionalAttributes: string[];
};

type ReactSpec = {
  componentName: string;
  propsInterface: ReactPropSpec[];
  variants: ReactVariantSpec[];
  a11y: ReactA11ySpec;
};

function mapBaseElement(role: string | undefined): {
  htmlTag: string;
  domElement: string;
  attrType: string;
} {
  switch (role) {
    case "button":
      return {
        htmlTag: "button",
        domElement: "HTMLButtonElement",
        attrType: "ButtonHTMLAttributes",
      };
    case "textbox":
      return { htmlTag: "input", domElement: "HTMLInputElement", attrType: "InputHTMLAttributes" };
    default:
      return { htmlTag: "div", domElement: "HTMLDivElement", attrType: "HTMLAttributes" };
  }
}

function escapeJsString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\"/g, '\\"');
}

function ensureVariantProps(props: ReactPropSpec[], variants: ReactVariantSpec[]): ReactPropSpec[] {
  const merged = new Map<string, ReactPropSpec>();

  for (const prop of props) {
    merged.set(prop.name, prop);
  }

  for (const variant of variants) {
    if (merged.has(variant.name)) {
      continue;
    }

    merged.set(variant.name, {
      name: variant.name,
      type: variant.values.map((value) => `"${value}"`).join(" | ") || "string",
      required: false,
      ...(variant.defaultValue !== undefined && {
        defaultValue: `"${escapeJsString(variant.defaultValue)}"`,
      }),
      description: `Variant: ${variant.name}`,
    });
  }

  return [...merged.values()].sort((a, b) => a.name.localeCompare(b.name));
}

function createA11yPropSpecs(a11y: ReactA11ySpec): ReactPropSpec[] {
  const attrs = [...new Set([...a11y.requiredAttributes, ...a11y.optionalAttributes])];

  return attrs
    .filter((attr) => attr.startsWith("aria-"))
    .map((attr) => ({
      name: attr,
      type: "string",
      required: a11y.requiredAttributes.includes(attr),
      description: `Accessibility attribute: ${attr}`,
    }));
}

export class ReactEmitter implements Emitter {
  readonly framework = "react";

  async emit(transformed: TransformedComponent): Promise<PipelineResult<GeneratedFile[]>> {
    const { componentName, propsInterface, variants, a11y } = transformed.spec as ReactSpec;
    const isOverlayComponent = ["dialog", "popover", "dropdown-menu", "select"].includes(
      transformed.componentId,
    );
    const allProps = ensureVariantProps(propsInterface, variants);
    const a11yProps = createA11yPropSpecs(a11y);
    const allPropsWithA11y = [...allProps, ...a11yProps].filter((prop) => prop.name !== "children");

    const primaryRole = a11y.roles[0];
    const roleAttr = primaryRole ? ` role="${primaryRole}"` : "";
    const baseElement = mapBaseElement(primaryRole);

    const propsLines = allPropsWithA11y.map((p) => {
      const opt = p.required ? "" : "?";
      const comment = p.description ? `  /** ${p.description} */\n` : "";
      return `${comment}  ${p.name}${opt}: ${p.type};`;
    });

    const defaultsLines = allPropsWithA11y
      .filter((p) => p.defaultValue !== undefined)
      .map((p) => `  ${p.name} = ${p.defaultValue},`);

    const variantNames = variants.map((variant) => variant.name);
    const variantDataAttrs = variantNames
      .map((name) => `        data-${name}={${name} !== undefined ? ${name} : undefined}`)
      .join("\n");

    const attributePropType = `React.${baseElement.attrType}<${baseElement.domElement}>`;

    const classNameBase = escapeJsString(transformed.componentId);

    const overlayImports = isOverlayComponent ? 'import { createPortal } from "react-dom";\n' : "";

    const overlayState = isOverlayComponent
      ? `    const overlayRef = React.useRef<${baseElement.domElement} | null>(null);
    const [open, setOpen] = React.useState(false);

    React.useEffect(() => {
      if (!open) return;

      const onKeyDown = (event: KeyboardEvent) => {
        if (event.key === "Escape") setOpen(false);
      };

      const trapFocus = (event: KeyboardEvent) => {
        if (event.key !== "Tab") return;
        const root = overlayRef.current;
        if (!root) return;

        const focusable = root.querySelectorAll<HTMLElement>(
          'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
        );
        if (focusable.length === 0) return;

        const first = focusable[0];
        const last = focusable[focusable.length - 1];

        if (event.shiftKey && document.activeElement === first) {
          event.preventDefault();
          last?.focus();
        } else if (!event.shiftKey && document.activeElement === last) {
          event.preventDefault();
          first?.focus();
        }
      };

      document.addEventListener("keydown", onKeyDown);
      document.addEventListener("keydown", trapFocus);
      return () => {
        document.removeEventListener("keydown", onKeyDown);
        document.removeEventListener("keydown", trapFocus);
      };
    }, [open]);

`
      : "";

    const overlayTriggerAttrs = isOverlayComponent
      ? `
        aria-hidden={!open}
        onClick={() => setOpen((value) => !value)}`
      : "";

    const overlayReturn = isOverlayComponent
      ? `    const overlayContent = (
      <${baseElement.htmlTag}
        ref={overlayRef}${roleAttr}
${variantDataAttrs}
        className={cn("${classNameBase}", className)}
        {...props}
      />
    );

    if (!open || typeof document === "undefined") {
      return (
        <${baseElement.htmlTag}
          ref={ref}${roleAttr}
${variantDataAttrs}
${overlayTriggerAttrs}
          className={cn("${classNameBase}", className)}
          {...props}
        />
      );
    }

    // Portal rendering strategy: overlays mount into document.body.
    return createPortal(overlayContent, document.body);`
      : `    return (
      <${baseElement.htmlTag}
        ref={ref}${roleAttr}
${variantDataAttrs}
        className={cn("${classNameBase}", className)}
        {...props}
      />
    );`;

    const content = `// @generated by shadcnui-foundry — DO NOT EDIT MANUALLY
// Run \`foundry generate ${transformed.componentId}\` to regenerate
import * as React from "react";
${overlayImports}import { cn } from "../utils/cn.js";

export interface ${componentName}Props extends ${attributePropType} {
${propsLines.join("\n")}
}

const ${componentName} = React.forwardRef<${baseElement.domElement}, ${componentName}Props>(
  function ${componentName}(
    {
${defaultsLines.join("\n")}
      className,
      ...props
    },
    ref
  ) {
${overlayState}${overlayReturn}
  }
);
${componentName}.displayName = "${componentName}";

export { ${componentName} };
`;

    const file: GeneratedFile = {
      path: `${transformed.componentId}/${componentName}.tsx`,
      content,
      componentId: transformed.componentId,
      framework: "react",
      generated: true,
      irHash: "",
    };

    return { success: true, data: [file] };
  }
}
